project:
  output-dir: docs
  render:
    - index.qmd
    - how-to/*.qmd
    - reference/*.qmd
    - reference/methodology/*.qmd
    - explanation/*.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    toc-depth: 3
    embed-resources: true
    standalone: true
    code-fold: false
    code-tools: false
